name: CI - Run Tests on Push

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main  

jobs:
  test:
    runs-on: ubuntu-latest  

    steps:
      
      - name: Checkout code
        uses: actions/checkout@v2

      
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.10' 

      
      - name: Install dependencies
        run: |
          python -m venv venv  # Create a virtual environment
          source venv/bin/activate  # Activate virtual environment
          pip install --upgrade pip  # Upgrade pip to the latest version
          pip install -r requirements.txt  # Install project dependencies

      
      - name: Run tests
        run: |
          source venv/bin/activate  # Make sure the virtual environment is activated
          pytest --maxfail=1 --disable-warnings -q  # Run tests (adjust as needed)

      
      - name: Upload test results as artifact
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: test-reports/
